/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useAtomValue } from "jotai";
import { answeringAtom, typingAtom } from "@/lib/atoms";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["Terrific_Bigery_(2)"]: THREE.Mesh;
    ["Terrific_Bigery_(5)"]: THREE.Mesh;
    ["Terrific_Bigery_(6)"]: THREE.Mesh;
    Mighty_Amberis: THREE.Mesh;
    Mighty_Amberis001: THREE.Mesh;
    Mighty_Amberis002: THREE.Mesh;
    Mighty_Amberis003: THREE.Mesh;
    Mighty_Amberis004: THREE.Mesh;
    Mighty_Amberis005: THREE.Mesh;
    Mighty_Amberis006: THREE.Mesh;
    ["Mighty_Amberis_(1)"]: THREE.Mesh;
  };
  materials: {};
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const answering = useAtomValue(answeringAtom);
  const typing = useAtomValue(typingAtom);

  const { nodes } = useGLTF("/Dalilil.glb") as unknown as GLTFResult;

  const bigSeif = useRef<THREE.Mesh>(null!);
  const smallSeif = useRef<THREE.Mesh>(null!);
  const circleRef = useRef<THREE.Mesh>(null!);
  const rotationDirection = useRef(1); // 1 for right, -1 for left
  useFrame(({ clock }) => {
    const time = clock.getElapsedTime();
    const speed = 5; // increase this for faster swing
    const amplitude = 0.1; // max rotation angle

    if (typing) {
      bigSeif.current.rotation.y = Math.sin(time * speed) * amplitude;
      //   circleRef.current.rotation.y += 0.01;
    } else {
      bigSeif.current.rotation.y = 0;
    }

    if (answering) {
      //   circleRef.current.rotation.y += 0.01;
      smallSeif.current.rotation.y += 0.01;
    } else {
      smallSeif.current.rotation.y = 0;
    }
  });

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          ref={circleRef}
          name="Terrific_Bigery_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Terrific_Bigery_(2)"].geometry}
          material={nodes["Terrific_Bigery_(2)"].material}
          position={[3.799, 5.774, -6.221]}
          rotation={[0.01, 0.044, 3.132]}
          scale={[1.361, 0.769, 1.315]}
        />
        <mesh
          ref={smallSeif}
          name="Terrific_Bigery_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Terrific_Bigery_(5)"].geometry}
          material={nodes["Terrific_Bigery_(5)"].material}
          position={[1.722, 2.961, -3.773]}
          rotation={[0, 0.048, -0.048]}
          scale={[0.932, 0.481, 1.157]}
        />
        <mesh
          name="Terrific_Bigery_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Terrific_Bigery_(6)"].geometry}
          material={nodes["Terrific_Bigery_(6)"].material}
          position={[4.666, 5.648, -3.444]}
          rotation={[-3.132, -0.038, -3.092]}
          scale={[-0.518, -2.6, -0.676]}
        />
        {/* <mesh
          name="Mighty_Amberis"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis.geometry}
          material={nodes.Mighty_Amberis.material}
          position={[3.693, -2.378, -2.095]}
          rotation={[0.056, -0.016, -0.023]}
          scale={[0.069, 0.032, 0.078]}
        />
        <mesh
          name="Mighty_Amberis001"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis001.geometry}
          material={nodes.Mighty_Amberis001.material}
          position={[3.693, -2.378, -2.095]}
          rotation={[0.056, -0.016, -0.023]}
          scale={[0.069, 0.032, 0.078]}
        />
        <mesh
          name="Mighty_Amberis002"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis002.geometry}
          material={nodes.Mighty_Amberis002.material}
          position={[3.693, -2.378, -2.095]}
          rotation={[0.056, -0.016, -0.023]}
          scale={[0.069, 0.032, 0.078]}
        />
        <mesh
          name="Mighty_Amberis003"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis003.geometry}
          material={nodes.Mighty_Amberis003.material}
          position={[3.206, 1.175, -1.038]}
          rotation={[-0.471, -1.538, -0.487]}
          scale={[0.075, 0.03, 0.063]}
        />
        <mesh
          name="Mighty_Amberis004"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis004.geometry}
          material={nodes.Mighty_Amberis004.material}
          position={[3.542, 0.145, -1.364]}
          rotation={[-3.14, 0.016, -3.138]}
          scale={[0.072, 0.037, 0.08]}
        />
        <mesh
          name="Mighty_Amberis005"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis005.geometry}
          material={nodes.Mighty_Amberis005.material}
          position={[3.693, -2.378, -2.095]}
          rotation={[0.056, -0.016, -0.023]}
          scale={[0.069, 0.032, 0.078]}
        />
        <mesh
          name="Mighty_Amberis006"
          castShadow
          receiveShadow
          geometry={nodes.Mighty_Amberis006.geometry}
          material={nodes.Mighty_Amberis006.material}
          position={[3.28, -0.965, -2.045]}
          rotation={[1.609, 1.537, -1.606]}
          scale={[0.087, 0.032, 0.061]}
        /> */}
        <mesh
          name="Mighty_Amberis_(1)"
          ref={bigSeif}
          castShadow
          receiveShadow
          geometry={nodes["Mighty_Amberis_(1)"].geometry}
          material={nodes["Mighty_Amberis_(1)"].material}
          position={[4.666, 5.648, -3.444]}
          rotation={[0, 0.021, -0.003]}
          scale={[0.437, 0.146, 0.488]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Dalilil.glb");
